### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [ThomasPohl/ioBroker.gotify#1]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/ThomasPohl/ioBroker.gotify

- [x] [E200] Not found on npm. Please publish
- [x] [E506] More non translated in german or russian words found in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [x] [E801] No repository about text found. Please go to "https://github.com/ThomasPohl/ioBroker.gotify", press the settings button beside the about title and add the description.
- [x] [E802] No topics found in the repository. Please go to "https://github.com/ThomasPohl/ioBroker.gotify", press the settings button beside the about title and add some topics.

I have also found warnings that may be fixed if possible.

- [x] [W400] Cannot find "gotify" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by pafade89** [comment]
Hi @ThomasPohl ,

Is it possible to include this great adapter in the stable release repo.

Would make it easier to update.

Cheers P

**Comment by ThomasPohl** [comment]
Hi @pafade89,
that's what I am trying to achieve. Next steps are to create a Testing-Thread in the iobroker forum. Depending on the reactions, we can move on to stable repo.

**Comment by pafade89** [comment]
Sounds very good. I have also tried to make a little advertising for your adapter and Gotify:

https://forum.iobroker.net/topic/67525/push-nachrichten-ohne-cloud-oder-proplan-gotify

Cheers P
