### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by skroob** [ThomasPohl/ioBroker.gotify#100]
**Describe the bug**  
The special characters are displayed incorrectly

**To Reproduce**  
See in script section onder blockly

**Screenshots & Logfiles**  
![2024-09-02_092042](https://github.com/user-attachments/assets/2a3a6b20-da88-4764-85fa-359743e07c3e)

**Versions:**  
 - Adapter version: 0.2.1
 - JS-Controller version: 8.8.2
 - Node version: 22.7.0
 - Operating system: linux

**Comment by ThomasPohl** [comment]
Might be connected to linux. On MacOs it looks like this:

![image](https://github.com/user-attachments/assets/022d680f-257d-4918-bb4a-29ac65e6a2fb)

**Comment by skroob** [comment]
I check this to day and your right. Now everything is correct. I think it was an small issue, thats solved in a linux update i made.

Thank you for your support!

**Comment by skroob** [comment]
Close...
