### ISSUE TITLE
iobroker notification- manager

### ISSUE THREAD

**Issue by HJRoe** [ThomasPohl/ioBroker.gotify#121]
my dear,
is it possible to add gotify to the iobroker notification-manager?
Currently you cannot select gotify as an adapter instance.
Thank You for your help
HJ

**Comment by ThomasPohl** [comment]
HI @HJRoe ,

thank you for this suggestion. I will have a look at it and see if thats feasible.

**Comment by ThomasPohl** [comment]
@HJRoe I just released 0.4.0. It includes the connection to notification-manager. Thanks for the idea.
