### ISSUE TITLE
Weitere Priorität hinzufügen

### ISSUE THREAD

**Issue by Kiter1988** [ThomasPohl/ioBroker.gotify#125]
Hallo, 
kein BugReport nur eine Frage. 

Ich wollte das Script um eine "kritische Priorität (10)" erweitern.
Habe dazu im blockly.js die entsprechenden Zeilen hinzugefügt. 

`Blockly.Words["gotify_prio_critical"] = { en: "critical", de: "Kritisch" };`

und 

`[Blockly.Translate("gotify_prio_critical"), "10"],`

leider kann ich diese Prioritäten dann nicht im sendto Block auswählen.
Muss ich noch etwas ändern ?

**Comment by ThomasPohl** [comment]
Hallo @Kiter1988,
das sollte so eigentlich ausreichen. Vielleicht musst du einmal den javascript-Adapter neustarten?

Wenn es klappt, wäre es super wenn du einen pull-Request erstellen würdest.

**Comment by Kiter1988** [comment]
Hi, 
kurz zur Erklärung, beim iPhone werden die kritischen Benachrichtigungen nur mit Stufe 10 ausgelöst, das möchte ich gerne für einige Dinge nutzen.

Es hat nicht geklappt. 
Selbst wenn ich die vorhandene hohe Stufe 8 mit der 10 tausche passiert nichts, trotz neustart iobroker bzw. javascript-adapter.

**Comment by ThomasPohl** [comment]
Ich baue das in die nächste Version ein. Für jetzt kannst du auch direkt mit Javascript arbeiten. Z.B. so:

```javascript
sendTo("gotify", "send", {
   priority: 10,
   contentType: 'text/plain',
   message: 'Kritischer Test'
});
```

**Comment by ThomasPohl** [comment]
@Kiter1988 Ich habe gerade 0.4.0 released. Sollte jetzt funktionieren. Bitte teste mal ob das so für dich passt.

**Comment by Kiter1988** [comment]
> @Kiter1988 Ich habe gerade 0.4.0 released. Sollte jetzt funktionieren. Bitte teste mal ob das so für dich passt.

Vielen Dank, Prio "kritisch" wird angezeigt und löst auch bei meinem ios Gerät den kritischen Alarm aus.
