### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.2.0

### ISSUE THREAD

**Issue by GermanBluefox** [ThomasPohl/ioBroker.gotify#32]
# Think about adding version 0.2.0 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.2.0** (30 days old)
**Installs**: stable=**0** (0%), latest=**11** (20%), total=**55**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by ThomasPohl** [comment]
@GermanBluefox I would love to add the version to stable repo. But there was not that much response to my test request:
https://forum.iobroker.net/topic/67848/test-neuer-adapter-gotify

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.2.0 but in the meantime an update to version 0.2.1 is suggested.

So this issue will be closed and replaced by an updated one.

@mcm1957 for evidence
