### ISSUE TITLE
Will be the project updated in the future ...

### ISSUE THREAD

**Issue by GameWatchProjects** [ThomasPohl/ioBroker.gotify#4]
Hello,

will be the project updated in the future and listed in the official IOBroker Adapter Repro (i don't install adapters from external sources) or is the project died before started?

**Comment by ThomasPohl** [comment]
Hello @GameWatchProjects ,

I didn't update the project since it didn't seem like there was anyone interested in the adapter.

If I find some time I will at leat make it compatible with the lastest version

**Comment by ThomasPohl** [comment]
A new version 0.1.0 has just been uploaded to npm
