### ISSUE TITLE
No error during initial instance creation.

### ISSUE THREAD

**Issue by pafade89** [ThomasPohl/ioBroker.gotify#44]
**Describe the bug**  
The following error always occurs when creating an instance for the first time: 'Cannot send notification while not configured.

**Expected behavior**  
I expect this error only when there is a configuration error during operation or when the instance is being saved for the first time without being configured. However, not before that.

**Screenshots & Logfiles**  
![image](https://github.com/ThomasPohl/ioBroker.gotify/assets/113902279/0e69ffd4-0104-41bd-b13d-4ee1ab20af20)

**Versions:**  
 - Adapter version: 0.2.0
 - JS-Controller version: 5.0.16
 - Node version: 18.18.2
 - Operating system: debian

Thank you in advanced 

Cheers P

**Comment by ThomasPohl** [comment]
Hi @pafade89 ,
you are right, that's not ideal. 
There should be not error-message directly after creating the instance. Furthermore the instance should not report that it is running, although it is not configured.

I'll check what I can do about that.

**Comment by pafade89** [comment]
@ThomasPohl 

That sounds great! I look forward to the customization.

**Comment by ThomasPohl** [comment]
Hi @pafade89,
please have a look at v0.2.1. The startup should look better now. Even if the adapter is not configured

**Comment by pafade89** [comment]
Hi @ThomasPohl,

thank you very much for your adjustment. The error no longer occurs only when a new instance is simply created. But currently the adapter does not recognize that the data for the app is incorrect when saving a new configured instance. Is it not possible to check if this data is correct beforehand?

```
gotify.6 | 2024-05-21 09:07:06.976 | info | Gotify adapter configured
gotify.6 | 2024-05-21 09:07:06.968 | info | starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.gotify, node: v18.20.1, js-controller: 5.0.19
```

This is what the log looks like even with incorrect data is entered in the adapter instance.
