### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.2.1

### ISSUE THREAD

**Issue by GermanBluefox** [ThomasPohl/ioBroker.gotify#84]
# Think about adding version 0.2.1 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.2.1** (30 days old)
**Installs**: stable=**0** (0%), latest=**40** (35.4%), total=**113**

Click to use [developer portal](https://www.iobroker.dev/adapter/gotify/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 0.2.1 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Is there any reason to delay adding this adapter to stable any longer?
Please drop a commit if you know any reason to refrain from adding.

**If there is no response until 13.7.2024 we could decide to add it anyway.**

**Comment by mcm1957** [comment]
fixing of errors listed at https://github.com/ThomasPohl/ioBroker.gotify/issues/88 required

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.2.1 but the current stable version is already 0.3.0.

So this issue should be closed.

@mcm1957 for evidence
